//
// NOTICE: This file is generated. Do not edit this file manually, please edit the template instead.
//
﻿using System.Windows.Forms;

namespace MattyControls
{
    public interface IMattyControl
    {
        void LocateInside(Control parent, MattyControl.Horizontal h = MattyControl.Horizontal.Left, MattyControl.Vertical v = MattyControl.Vertical.Top, int d = -1);
        void LocateFrom(Control other, MattyControl.Horizontal h = MattyControl.Horizontal.CopyLeft, MattyControl.Vertical v = MattyControl.Vertical.CopyTop, int d = -1);

        void AddLabel(string text, bool moveCtrl = true, int labelWidth = 0, int d = -1);

        void PositionRightOf(Control other, int d = -1);
        void PositionLeftOf(Control other, int d = -1);
        void PositionAbove(Control other, int d = -1);
        void PositionBelow(Control other, int d = -1);

        void PositionTopRightInside(Control parent, int d = -1);
        void PositionTopLeftInside(Control parent, int d = -1);
        void PositionBottomRightInside(Control parent, int d = -1);
        void PositionBottomLeftInside(Control parent, int d = -1);

        void StretchRightFactor(float factor);
        void StretchRightFixed(int amount);
        void StretchRightInside(Control parent, int d = -1);
        void StretchRightTo(Control other, int d = -1);

        void StretchDownFactor(float factor);
        void StretchDownFixed(int amount);
        void StretchDownInside(Control parent, int d = -1);
        void StretchDownTo(Control other, int d = -1);

        void StretchLeftFactor(float factor);
        void StretchLeftFixed(int amount);
        void StretchLeftInside(Control parent, int d = -1);
        void StretchLeftTo(Control other, int d = -1);

        void StretchUpFactor(float factor);
        void StretchUpFixed(int amount);
        void StretchUpInside(Control parent, int d = -1);
        void StretchUpTo(Control other, int d = -1);

        void MoveRight(int amount);
        void MoveDown(int amount);
        void MoveLeft(int amount);
        void MoveUp(int amount);
    }
}
